### ISSUE TITLE
Missing support for Java arguments

### ISSUE THREAD

**Issue by Okazakee** [TheRemote/Legendary-Java-Minecraft-Paper#1]
This is the best container that fits my needs, this is a really good job, there is only one thing i miss tho, i don't know if it is supported under the hood, but i would like to set an env variable for java args to get inserted on start script (like the max memory one).

Thanks in advance.

**Comment by TheRemote** [comment]
Hey Okazakee,

Thanks for the kind feedback on the script!  I'm glad it's suiting your needs for the most part.

Can you give me an idea of what kind of arguments you are wanting to insert?  I can probably add an environment variable to insert a generic argument that you specify as well but I'm wondering what you are wanting to set that isn't there as maybe there's some common ones I should add.

Thanks a ton for the feedback!

**Comment by Okazakee** [comment]
Thanks for the response, what I am trying to tell, is that someone who wants to even try to set arguments for launching the jar file, just cannot do it. I don't know much about java args, but I was wondering to try suggested args found on paper forums, it would be set like "JAVA_ARGS = -args" in portainer env settings, you have to judge if it would add value to your docker image, it was just a suggestion. I am sure you already set essentials ones and everything works flawlessly.
Whichever decision you take, it still is the best docker image for paper.

**Comment by TheRemote** [comment]
Closing for now but if this is still needed by anyone please let me know!
